en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Digicomlab. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Digicomlab"
  description: "Site Description"
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      # text: "Contact Us"
      # link: "/example-page/"
    footer_cta:
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "People"
      url: "/about/"
      weight: 1
    - identifier: "events"
      name: "Events"
      url: "/events/"
      weight: 2
    - identifier: "projects"
      name: "Research"
      url: "/projects/"
      weight: 3
    - identifier: "fundings"
      name: "Fundings"
      url: ""
      weight: 4
    - identifier: "fundings-1"
      name: "Seed Fundings"
      url: "/seedfunding/"
      weight: 1
      post: "Some words"
      parent: "fundings"
    - identifier: "fundings-2"
      name: "Thesis Grant"
      url: "/thesisgrant/"
      weight: 2
      parent: "fundings"
